compressionLevel: 9
enableColors: true
enableHyperlinks: true
enableMessageNames: false
enableProgressBars: true
enableScripts: true
enableTelemetry: true
enableTimers: false
lockfileFilename: package.lock
nodeLinker: pnp
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
pnpEnableEsmLoader: true
pnpMode: strict
progressBarStyle: default
yarnPath: .yarn/releases/yarn-3.2.2.cjs
